"""
Exercise database with 80+ exercises across all major muscle groups.
Each exercise includes muscle group, equipment, difficulty, instructions, and alternatives.
"""

from typing import Optional

EXERCISE_DATABASE: list[dict] = [
    # === CHEST ===
    {
        "name": "Barbell Bench Press",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "instructions": "Lie on a flat bench, grip the barbell slightly wider than shoulder width. Lower the bar to mid-chest, pause, then press up to full arm extension. Keep feet flat on floor and maintain a slight arch in lower back.",
        "alternatives": ["Dumbbell Bench Press", "Push-ups", "Machine Chest Press"],
    },
    {
        "name": "Dumbbell Bench Press",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Lie on a flat bench with a dumbbell in each hand at chest level. Press the dumbbells up until arms are extended, then lower back to chest level with control.",
        "alternatives": ["Barbell Bench Press", "Push-ups", "Machine Chest Press"],
    },
    {
        "name": "Incline Dumbbell Press",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders", "triceps"],
        "equipment": "dumbbells",
        "difficulty": "intermediate",
        "instructions": "Set bench to 30-45 degree incline. Press dumbbells from shoulder level to full extension overhead. Focus on squeezing upper chest at the top.",
        "alternatives": ["Incline Barbell Press", "Low-to-High Cable Fly"],
    },
    {
        "name": "Push-ups",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders", "core"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Start in plank position with hands slightly wider than shoulders. Lower body until chest nearly touches floor, then push back up. Keep core tight and body in a straight line.",
        "alternatives": ["Knee Push-ups", "Dumbbell Bench Press", "Wall Push-ups"],
    },
    {
        "name": "Dumbbell Fly",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders"],
        "equipment": "dumbbells",
        "difficulty": "intermediate",
        "instructions": "Lie on flat bench with dumbbells extended above chest, palms facing each other. Lower arms out to sides in a wide arc until you feel a stretch in chest. Bring dumbbells back together.",
        "alternatives": ["Cable Fly", "Pec Deck Machine"],
    },
    {
        "name": "Cable Crossover",
        "muscle_group": "chest",
        "secondary_muscles": ["shoulders"],
        "equipment": "cables",
        "difficulty": "intermediate",
        "instructions": "Stand between cable stations with pulleys set high. Step forward, grab handles, and bring hands together in front of chest in a hugging motion. Squeeze chest at the bottom.",
        "alternatives": ["Dumbbell Fly", "Pec Deck Machine"],
    },
    {
        "name": "Dips (Chest Focus)",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "instructions": "Using parallel bars, lean forward slightly. Lower body until upper arms are parallel to floor, then press back up. Forward lean targets chest more than triceps.",
        "alternatives": ["Decline Push-ups", "Decline Dumbbell Press"],
    },
    {
        "name": "Machine Chest Press",
        "muscle_group": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment": "machines",
        "difficulty": "beginner",
        "instructions": "Sit in the machine with handles at chest height. Push handles forward until arms are extended, then return with control. Keep back against pad.",
        "alternatives": ["Dumbbell Bench Press", "Push-ups"],
    },

    # === BACK ===
    {
        "name": "Barbell Deadlift",
        "muscle_group": "back",
        "secondary_muscles": ["legs", "core"],
        "equipment": "barbell",
        "difficulty": "advanced",
        "instructions": "Stand with feet hip-width apart, grip barbell outside knees. Keep back flat, drive through heels, and stand up by extending hips and knees simultaneously. Lower with control.",
        "alternatives": ["Romanian Deadlift", "Trap Bar Deadlift", "Dumbbell Deadlift"],
    },
    {
        "name": "Pull-ups",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "core"],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "instructions": "Hang from a bar with palms facing away, hands slightly wider than shoulders. Pull body up until chin clears the bar, then lower with control.",
        "alternatives": ["Lat Pulldown", "Assisted Pull-ups", "Resistance Band Pull-ups"],
    },
    {
        "name": "Lat Pulldown",
        "muscle_group": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "cables",
        "difficulty": "beginner",
        "instructions": "Sit at lat pulldown machine with thighs secured under pads. Grab bar with wide overhand grip. Pull bar down to upper chest, squeezing shoulder blades together. Return slowly.",
        "alternatives": ["Pull-ups", "Resistance Band Pulldown"],
    },
    {
        "name": "Barbell Bent-Over Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "core"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "instructions": "Hinge forward at hips with barbell hanging at arm's length. Pull bar to lower chest, squeezing shoulder blades together. Keep back flat and core braced throughout.",
        "alternatives": ["Dumbbell Row", "Cable Row", "T-Bar Row"],
    },
    {
        "name": "Dumbbell Single-Arm Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Place one knee and hand on bench for support. Row dumbbell from arm's length to hip, squeezing shoulder blade. Lower with control. Complete all reps then switch sides.",
        "alternatives": ["Barbell Bent-Over Row", "Cable Row"],
    },
    {
        "name": "Seated Cable Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "cables",
        "difficulty": "beginner",
        "instructions": "Sit at cable row station with feet on platform. Pull handle to lower chest, squeezing shoulder blades. Extend arms with control. Keep torso upright throughout.",
        "alternatives": ["Dumbbell Row", "Barbell Row"],
    },
    {
        "name": "Face Pull",
        "muscle_group": "back",
        "secondary_muscles": ["shoulders"],
        "equipment": "cables",
        "difficulty": "beginner",
        "instructions": "Set cable at face height with rope attachment. Pull rope toward face, separating hands as you pull. Squeeze rear delts and rotate hands outward at the end.",
        "alternatives": ["Reverse Fly", "Band Pull-Apart"],
    },
    {
        "name": "T-Bar Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps", "core"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "instructions": "Straddle the T-bar or landmine setup. Bend at hips, grip the handle, and row the weight to your chest. Keep back flat and core engaged.",
        "alternatives": ["Barbell Row", "Dumbbell Row"],
    },
    {
        "name": "Superman Hold",
        "muscle_group": "back",
        "secondary_muscles": ["core"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Lie face down on the floor. Simultaneously lift arms, chest, and legs off the ground. Hold for 2-3 seconds, squeezing lower back. Lower with control.",
        "alternatives": ["Back Extension", "Bird Dog"],
    },

    # === SHOULDERS ===
    {
        "name": "Overhead Press (Barbell)",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps", "core"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "instructions": "Stand with barbell at shoulder height, grip slightly wider than shoulders. Press bar overhead until arms are fully extended. Lower with control back to shoulders.",
        "alternatives": ["Dumbbell Shoulder Press", "Machine Shoulder Press"],
    },
    {
        "name": "Dumbbell Shoulder Press",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Sit or stand with dumbbells at shoulder height, palms facing forward. Press both dumbbells overhead until arms are extended. Lower with control.",
        "alternatives": ["Overhead Press", "Arnold Press", "Machine Shoulder Press"],
    },
    {
        "name": "Lateral Raise",
        "muscle_group": "shoulders",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Stand with dumbbells at sides. Raise arms out to sides until parallel to floor, leading with elbows. Lower slowly. Avoid swinging or using momentum.",
        "alternatives": ["Cable Lateral Raise", "Machine Lateral Raise"],
    },
    {
        "name": "Front Raise",
        "muscle_group": "shoulders",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Stand with dumbbells in front of thighs. Raise one or both arms forward to shoulder height with a slight bend in elbows. Lower with control.",
        "alternatives": ["Cable Front Raise", "Plate Front Raise"],
    },
    {
        "name": "Reverse Fly",
        "muscle_group": "shoulders",
        "secondary_muscles": ["back"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Bend forward at hips with dumbbells hanging below. Raise arms out to sides, squeezing shoulder blades together. Focus on rear delts. Lower slowly.",
        "alternatives": ["Face Pull", "Cable Reverse Fly"],
    },
    {
        "name": "Arnold Press",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment": "dumbbells",
        "difficulty": "intermediate",
        "instructions": "Start with dumbbells at shoulder height, palms facing you. As you press up, rotate palms to face forward at the top. Reverse on the way down.",
        "alternatives": ["Dumbbell Shoulder Press", "Overhead Press"],
    },
    {
        "name": "Upright Row",
        "muscle_group": "shoulders",
        "secondary_muscles": ["biceps"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "instructions": "Hold barbell with narrow grip in front of thighs. Pull bar up along body to chin level, leading with elbows. Lower with control. Keep bar close to body.",
        "alternatives": ["Dumbbell Upright Row", "Cable Upright Row"],
    },
    {
        "name": "Pike Push-ups",
        "muscle_group": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "instructions": "Start in downward dog position with hips high. Bend elbows to lower head toward floor, then push back up. The more vertical your torso, the harder the exercise.",
        "alternatives": ["Dumbbell Shoulder Press", "Handstand Push-ups (advanced)"],
    },

    # === BICEPS ===
    {
        "name": "Barbell Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "equipment": "barbell",
        "difficulty": "beginner",
        "instructions": "Stand with barbell at arm's length, underhand grip shoulder-width apart. Curl bar to shoulders, keeping elbows pinned to sides. Lower with control.",
        "alternatives": ["Dumbbell Curl", "EZ-Bar Curl", "Cable Curl"],
    },
    {
        "name": "Dumbbell Bicep Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Stand with dumbbells at sides, palms forward. Curl both dumbbells to shoulders while keeping elbows stationary. Lower slowly. Can alternate arms.",
        "alternatives": ["Barbell Curl", "Hammer Curl", "Cable Curl"],
    },
    {
        "name": "Hammer Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Stand with dumbbells at sides, palms facing each other (neutral grip). Curl dumbbells to shoulders. This targets brachialis and brachioradialis more than standard curls.",
        "alternatives": ["Dumbbell Curl", "Cross-Body Hammer Curl"],
    },
    {
        "name": "Concentration Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Sit on bench, brace elbow against inner thigh. Curl dumbbell to shoulder with strict form. Squeeze bicep at top. Lower slowly. No swinging allowed.",
        "alternatives": ["Preacher Curl", "Dumbbell Curl"],
    },
    {
        "name": "Preacher Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "instructions": "Sit at preacher bench with upper arms on pad. Curl barbell to shoulders, then lower until arms are nearly straight. The pad eliminates momentum.",
        "alternatives": ["Concentration Curl", "Machine Preacher Curl"],
    },
    {
        "name": "Cable Curl",
        "muscle_group": "biceps",
        "secondary_muscles": [],
        "equipment": "cables",
        "difficulty": "beginner",
        "instructions": "Stand facing low cable with straight bar or EZ-bar attachment. Curl bar to shoulders, keeping elbows at sides. Lower with control. Constant tension throughout.",
        "alternatives": ["Barbell Curl", "Dumbbell Curl"],
    },

    # === TRICEPS ===
    {
        "name": "Tricep Pushdown",
        "muscle_group": "triceps",
        "secondary_muscles": [],
        "equipment": "cables",
        "difficulty": "beginner",
        "instructions": "Stand at cable station with high pulley and rope or bar attachment. Push handle down until arms are fully extended. Keep elbows pinned to sides. Return slowly.",
        "alternatives": ["Overhead Tricep Extension", "Diamond Push-ups"],
    },
    {
        "name": "Overhead Tricep Extension",
        "muscle_group": "triceps",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Hold one dumbbell with both hands overhead. Lower it behind your head by bending elbows. Extend arms back to starting position. Keep elbows close to head.",
        "alternatives": ["Tricep Pushdown", "Skull Crushers"],
    },
    {
        "name": "Skull Crushers (Lying Tricep Extension)",
        "muscle_group": "triceps",
        "secondary_muscles": [],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "instructions": "Lie on bench with barbell extended above chest. Lower bar toward forehead by bending elbows only. Extend back to starting position. Keep upper arms stationary.",
        "alternatives": ["Overhead Tricep Extension", "Tricep Pushdown"],
    },
    {
        "name": "Diamond Push-ups",
        "muscle_group": "triceps",
        "secondary_muscles": ["chest"],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "instructions": "Assume push-up position with hands close together, forming a diamond shape with thumbs and index fingers. Lower chest to hands and push back up. Keep elbows close to body.",
        "alternatives": ["Tricep Pushdown", "Bench Dips"],
    },
    {
        "name": "Tricep Kickback",
        "muscle_group": "triceps",
        "secondary_muscles": [],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Bend forward with upper arm parallel to floor. Extend forearm back until arm is straight, squeezing tricep. Lower slowly. Keep upper arm still.",
        "alternatives": ["Tricep Pushdown", "Overhead Extension"],
    },
    {
        "name": "Close-Grip Bench Press",
        "muscle_group": "triceps",
        "secondary_muscles": ["chest", "shoulders"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "instructions": "Lie on bench and grip barbell with hands shoulder-width or closer. Lower bar to lower chest, keeping elbows close. Press back up. Emphasizes triceps over chest.",
        "alternatives": ["Diamond Push-ups", "Skull Crushers"],
    },

    # === LEGS - Quadriceps ===
    {
        "name": "Barbell Back Squat",
        "muscle_group": "legs",
        "secondary_muscles": ["core"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "instructions": "Place barbell on upper back/traps. Stand with feet shoulder-width apart. Squat down until thighs are parallel to floor. Drive through heels to stand. Keep chest up and core braced.",
        "alternatives": ["Goblet Squat", "Leg Press", "Bodyweight Squat"],
    },
    {
        "name": "Goblet Squat",
        "muscle_group": "legs",
        "secondary_muscles": ["core"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Hold a dumbbell or kettlebell at chest level. Squat down with feet shoulder-width apart until thighs are parallel. Keep weight on heels and chest upright. Stand back up.",
        "alternatives": ["Bodyweight Squat", "Barbell Squat"],
    },
    {
        "name": "Leg Press",
        "muscle_group": "legs",
        "secondary_muscles": [],
        "equipment": "machines",
        "difficulty": "beginner",
        "instructions": "Sit in leg press machine with feet shoulder-width on platform. Lower platform by bending knees to 90 degrees. Press back up without locking knees. Keep back flat against pad.",
        "alternatives": ["Barbell Squat", "Goblet Squat"],
    },
    {
        "name": "Walking Lunges",
        "muscle_group": "legs",
        "secondary_muscles": ["core"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Step forward into a lunge, lowering back knee toward floor. Push off front foot and step forward into next lunge. Alternate legs. Keep torso upright.",
        "alternatives": ["Reverse Lunges", "Bulgarian Split Squat"],
    },
    {
        "name": "Bulgarian Split Squat",
        "muscle_group": "legs",
        "secondary_muscles": ["core"],
        "equipment": "dumbbells",
        "difficulty": "intermediate",
        "instructions": "Place rear foot on a bench behind you. Lower into a single-leg squat on front leg until thigh is parallel. Drive up through front heel. Complete all reps then switch.",
        "alternatives": ["Walking Lunges", "Step-ups"],
    },
    {
        "name": "Leg Extension",
        "muscle_group": "legs",
        "secondary_muscles": [],
        "equipment": "machines",
        "difficulty": "beginner",
        "instructions": "Sit in leg extension machine with pad on lower shins. Extend legs until straight, squeezing quads at top. Lower slowly with control. Don't use momentum.",
        "alternatives": ["Bodyweight Squats", "Wall Sit"],
    },
    {
        "name": "Bodyweight Squat",
        "muscle_group": "legs",
        "secondary_muscles": ["core"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Stand with feet shoulder-width apart, arms extended forward. Squat down until thighs are parallel, keeping weight on heels. Stand back up. Keep chest up throughout.",
        "alternatives": ["Goblet Squat", "Wall Sit"],
    },
    {
        "name": "Step-ups",
        "muscle_group": "legs",
        "secondary_muscles": ["core"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Stand facing a sturdy bench or step. Step up with one foot, drive through heel to stand on top. Step down with control. Alternate legs or complete one side first.",
        "alternatives": ["Walking Lunges", "Bulgarian Split Squat"],
    },

    # === LEGS - Hamstrings & Glutes ===
    {
        "name": "Romanian Deadlift",
        "muscle_group": "legs",
        "secondary_muscles": ["back", "core"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "instructions": "Stand with barbell at hip height. Hinge at hips, pushing them back while lowering bar along legs. Feel stretch in hamstrings. Return to standing by driving hips forward. Keep back flat.",
        "alternatives": ["Dumbbell RDL", "Good Mornings"],
    },
    {
        "name": "Leg Curl (Lying)",
        "muscle_group": "legs",
        "secondary_muscles": [],
        "equipment": "machines",
        "difficulty": "beginner",
        "instructions": "Lie face down on leg curl machine with pad above heels. Curl heels toward glutes, squeezing hamstrings. Lower slowly with control.",
        "alternatives": ["Romanian Deadlift", "Nordic Hamstring Curl"],
    },
    {
        "name": "Hip Thrust",
        "muscle_group": "legs",
        "secondary_muscles": ["core"],
        "equipment": "barbell",
        "difficulty": "intermediate",
        "instructions": "Sit on floor with upper back against bench. Place barbell over hips. Drive through heels to lift hips until body forms a straight line from shoulders to knees. Squeeze glutes at top.",
        "alternatives": ["Glute Bridge", "Single-Leg Hip Thrust"],
    },
    {
        "name": "Glute Bridge",
        "muscle_group": "legs",
        "secondary_muscles": ["core"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Lie on back with knees bent and feet flat. Drive through heels to lift hips until body forms a straight line from shoulders to knees. Squeeze glutes at top. Lower with control.",
        "alternatives": ["Hip Thrust", "Single-Leg Glute Bridge"],
    },
    {
        "name": "Calf Raise (Standing)",
        "muscle_group": "legs",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Stand on edge of a step with heels hanging off. Rise up on toes as high as possible, squeezing calves. Lower heels below the step for a full stretch. Can add weight.",
        "alternatives": ["Seated Calf Raise", "Donkey Calf Raise"],
    },
    {
        "name": "Sumo Squat",
        "muscle_group": "legs",
        "secondary_muscles": ["core"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Stand with feet wider than shoulder-width, toes pointed out at 45 degrees. Hold dumbbell between legs. Squat down, keeping chest up and knees tracking over toes. Stand back up.",
        "alternatives": ["Goblet Squat", "Plie Squat"],
    },

    # === CORE ===
    {
        "name": "Plank",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Hold a push-up position on forearms with body in a straight line from head to heels. Engage core, squeeze glutes. Hold for prescribed time. Don't let hips sag or pike.",
        "alternatives": ["Side Plank", "Dead Bug"],
    },
    {
        "name": "Russian Twist",
        "muscle_group": "core",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Sit with knees bent, lean back slightly. Hold weight or clasp hands. Rotate torso side to side, touching the floor on each side. Keep feet elevated for more challenge.",
        "alternatives": ["Bicycle Crunch", "Cable Woodchop"],
    },
    {
        "name": "Hanging Leg Raise",
        "muscle_group": "core",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "instructions": "Hang from a pull-up bar. Raise legs straight out in front until parallel to floor. Lower with control. Avoid swinging. Bend knees to make it easier.",
        "alternatives": ["Lying Leg Raise", "Captain's Chair Leg Raise"],
    },
    {
        "name": "Dead Bug",
        "muscle_group": "core",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Lie on back with arms extended up and knees bent 90 degrees. Slowly extend opposite arm and leg toward floor while keeping lower back pressed into ground. Return and switch sides.",
        "alternatives": ["Bird Dog", "Plank"],
    },
    {
        "name": "Cable Woodchop",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "cables",
        "difficulty": "intermediate",
        "instructions": "Set cable high. Stand sideways to cable. Pull handle diagonally across body from high to low, rotating torso. Control the return. Complete all reps then switch sides.",
        "alternatives": ["Russian Twist", "Medicine Ball Slam"],
    },
    {
        "name": "Ab Rollout",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "bodyweight",
        "difficulty": "advanced",
        "instructions": "Kneel with ab wheel or barbell in front. Roll forward, extending body as far as possible while keeping core tight. Pull back to starting position using abs. Don't let hips sag.",
        "alternatives": ["Plank", "Body Saw"],
    },
    {
        "name": "Mountain Climbers",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders", "legs"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Start in push-up position. Alternate driving knees toward chest in a running motion. Keep hips down and core engaged. Increase speed for more cardio challenge.",
        "alternatives": ["Plank", "High Knees"],
    },
    {
        "name": "Bicycle Crunch",
        "muscle_group": "core",
        "secondary_muscles": [],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Lie on back with hands behind head, legs elevated. Bring opposite elbow to opposite knee while extending the other leg. Alternate in a cycling motion. Don't pull on neck.",
        "alternatives": ["Russian Twist", "Crunch"],
    },
    {
        "name": "Pallof Press",
        "muscle_group": "core",
        "secondary_muscles": [],
        "equipment": "cables",
        "difficulty": "beginner",
        "instructions": "Stand sideways to cable set at chest height. Hold handle at chest. Press arms straight out, resisting the rotational pull. Hold for a moment, return to chest. Anti-rotation exercise.",
        "alternatives": ["Plank", "Dead Bug"],
    },
    {
        "name": "Side Plank",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Lie on side, prop up on forearm with elbow under shoulder. Lift hips to form a straight line. Hold for prescribed time. Engage obliques. Switch sides.",
        "alternatives": ["Plank", "Russian Twist"],
    },

    # === CARDIO ===
    {
        "name": "Jumping Jacks",
        "muscle_group": "cardio",
        "secondary_muscles": ["legs", "shoulders"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Stand with feet together, arms at sides. Jump feet wide while raising arms overhead. Jump back to starting position. Maintain a steady rhythm.",
        "alternatives": ["High Knees", "Burpees"],
    },
    {
        "name": "Burpees",
        "muscle_group": "cardio",
        "secondary_muscles": ["chest", "legs", "core"],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "instructions": "From standing, squat down and place hands on floor. Jump feet back to plank. Do a push-up. Jump feet to hands. Explosively jump up with arms overhead. Repeat.",
        "alternatives": ["Squat Jumps", "Mountain Climbers"],
    },
    {
        "name": "High Knees",
        "muscle_group": "cardio",
        "secondary_muscles": ["legs", "core"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Run in place, driving knees as high as possible. Pump arms. Keep core tight and maintain an upright posture. Aim for a quick, light cadence.",
        "alternatives": ["Jumping Jacks", "Butt Kicks"],
    },
    {
        "name": "Box Jumps",
        "muscle_group": "cardio",
        "secondary_muscles": ["legs"],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "instructions": "Stand facing a sturdy box. Bend knees, swing arms, and jump onto the box. Land softly with both feet. Stand fully, then step down. Don't bounce at the bottom.",
        "alternatives": ["Squat Jumps", "Step-ups"],
    },
    {
        "name": "Jump Rope",
        "muscle_group": "cardio",
        "secondary_muscles": ["legs", "shoulders"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Hold rope handles at hip height. Swing rope overhead and jump as it passes under feet. Land on balls of feet. Keep jumps small and elbows close to body.",
        "alternatives": ["Jumping Jacks", "High Knees"],
    },
    {
        "name": "Battle Rope Waves",
        "muscle_group": "cardio",
        "secondary_muscles": ["shoulders", "core"],
        "equipment": "resistance_bands",
        "difficulty": "intermediate",
        "instructions": "Hold one end of rope in each hand. Create alternating waves by rapidly raising and lowering arms. Keep core engaged and knees slightly bent. Maintain intensity.",
        "alternatives": ["Burpees", "Mountain Climbers"],
    },
    {
        "name": "Treadmill Running",
        "muscle_group": "cardio",
        "secondary_muscles": ["legs"],
        "equipment": "machines",
        "difficulty": "beginner",
        "instructions": "Set treadmill to desired speed and incline. Maintain an upright posture with arms swinging naturally. Land midfoot. Start with a warm-up pace and gradually increase.",
        "alternatives": ["Outdoor Running", "Cycling", "Elliptical"],
    },
    {
        "name": "Stationary Cycling",
        "muscle_group": "cardio",
        "secondary_muscles": ["legs"],
        "equipment": "machines",
        "difficulty": "beginner",
        "instructions": "Adjust seat height so leg is slightly bent at bottom of pedal stroke. Maintain steady cadence. Adjust resistance for desired intensity. Keep upper body relaxed.",
        "alternatives": ["Treadmill Running", "Rowing Machine"],
    },
    {
        "name": "Rowing Machine",
        "muscle_group": "cardio",
        "secondary_muscles": ["back", "legs", "core"],
        "equipment": "machines",
        "difficulty": "beginner",
        "instructions": "Sit on rower, strap feet in. Drive with legs first, then lean back slightly and pull handle to lower chest. Extend arms, lean forward, and bend knees to return.",
        "alternatives": ["Stationary Cycling", "Treadmill"],
    },
    {
        "name": "Outdoor Walking (Brisk)",
        "muscle_group": "cardio",
        "secondary_muscles": ["legs"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Walk at a brisk pace (3.5-4.5 mph). Swing arms naturally. Maintain good posture. Aim for at least 30 minutes. Great for active recovery and beginners.",
        "alternatives": ["Treadmill Walking", "Light Jogging"],
    },
    {
        "name": "Elliptical Trainer",
        "muscle_group": "cardio",
        "secondary_muscles": ["legs", "shoulders"],
        "equipment": "machines",
        "difficulty": "beginner",
        "instructions": "Stand on pedals and grip handles. Move in a smooth elliptical motion. Adjust resistance and incline for intensity. Low impact alternative to running.",
        "alternatives": ["Stationary Cycling", "Treadmill"],
    },

    # === FLEXIBILITY / WARMUP ===
    {
        "name": "Inchworm",
        "muscle_group": "core",
        "secondary_muscles": ["shoulders", "legs"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Stand tall, bend forward and walk hands out to plank position. Walk hands back to feet and stand up. Stretches hamstrings and warms up shoulders and core.",
        "alternatives": ["World's Greatest Stretch"],
    },
    {
        "name": "Bodyweight Good Morning",
        "muscle_group": "legs",
        "secondary_muscles": ["back"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Stand with hands behind head. Hinge at hips, pushing them back while keeping back flat. Lower torso until parallel to floor. Return to standing. Stretches hamstrings.",
        "alternatives": ["Romanian Deadlift", "Cat-Cow"],
    },
    {
        "name": "Wall Sit",
        "muscle_group": "legs",
        "secondary_muscles": ["core"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Lean against a wall and slide down until thighs are parallel to floor, knees at 90 degrees. Hold this position. Keep back flat against wall. Great isometric leg exercise.",
        "alternatives": ["Bodyweight Squat", "Goblet Squat"],
    },

    # === ADDITIONAL EXERCISES ===
    {
        "name": "Dumbbell Pullover",
        "muscle_group": "chest",
        "secondary_muscles": ["back"],
        "equipment": "dumbbells",
        "difficulty": "intermediate",
        "instructions": "Lie on a bench with a dumbbell held above chest with both hands. Lower the weight behind head in an arc until you feel a stretch. Pull back over chest using chest and lats.",
        "alternatives": ["Cable Pullover", "Dumbbell Fly"],
    },
    {
        "name": "Reverse Lunge",
        "muscle_group": "legs",
        "secondary_muscles": ["core"],
        "equipment": "bodyweight",
        "difficulty": "beginner",
        "instructions": "Stand tall, step one foot back and lower into a lunge. Back knee should nearly touch the ground. Push through front heel to return to standing. Alternate legs.",
        "alternatives": ["Walking Lunges", "Bulgarian Split Squat"],
    },
    {
        "name": "Farmer's Walk",
        "muscle_group": "core",
        "secondary_muscles": ["legs", "shoulders"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Hold heavy dumbbells at your sides. Walk with controlled steps for a set distance or time. Keep shoulders back, core braced, and stand tall. Builds grip and full-body stability.",
        "alternatives": ["Suitcase Carry", "Plank"],
    },
    {
        "name": "Squat Jump",
        "muscle_group": "cardio",
        "secondary_muscles": ["legs"],
        "equipment": "bodyweight",
        "difficulty": "intermediate",
        "instructions": "Perform a bodyweight squat, then explosively jump up as high as possible. Land softly with bent knees and immediately go into the next rep. Keep chest up.",
        "alternatives": ["Box Jumps", "Bodyweight Squat"],
    },
    {
        "name": "Seated Calf Raise",
        "muscle_group": "legs",
        "secondary_muscles": [],
        "equipment": "machines",
        "difficulty": "beginner",
        "instructions": "Sit in the calf raise machine with pad on thighs. Raise heels as high as possible, squeezing calves. Lower slowly for a full stretch. Targets the soleus muscle.",
        "alternatives": ["Calf Raise (Standing)", "Single-Leg Calf Raise"],
    },
    {
        "name": "Chest Supported Row",
        "muscle_group": "back",
        "secondary_muscles": ["biceps"],
        "equipment": "dumbbells",
        "difficulty": "beginner",
        "instructions": "Lie face down on an incline bench. Let dumbbells hang below. Row both dumbbells to your sides, squeezing shoulder blades together. Lower with control. Eliminates momentum.",
        "alternatives": ["Dumbbell Single-Arm Row", "Seated Cable Row"],
    },
]


def get_all_exercises() -> list[dict]:
    """Return all exercises in the database."""
    return EXERCISE_DATABASE


def get_exercises_by_muscle_group(muscle_group: str) -> list[dict]:
    """Get exercises for a specific muscle group."""
    return [e for e in EXERCISE_DATABASE if e["muscle_group"] == muscle_group]


def get_exercises_by_equipment(equipment: str) -> list[dict]:
    """Get exercises available with specific equipment."""
    return [e for e in EXERCISE_DATABASE if e["equipment"] == equipment]


def get_exercises_by_difficulty(difficulty: str) -> list[dict]:
    """Get exercises at a specific difficulty level."""
    return [e for e in EXERCISE_DATABASE if e["difficulty"] == difficulty]


def get_exercises_filtered(
    muscle_group: Optional[str] = None,
    equipment: Optional[list[str]] = None,
    difficulty: Optional[str] = None,
) -> list[dict]:
    """Get exercises matching multiple filters."""
    results = EXERCISE_DATABASE

    if muscle_group:
        results = [e for e in results if e["muscle_group"] == muscle_group]

    if equipment:
        results = [e for e in results if e["equipment"] in equipment]

    if difficulty:
        diff_order = {"beginner": 0, "intermediate": 1, "advanced": 2}
        max_diff = diff_order.get(difficulty, 2)
        results = [e for e in results if diff_order.get(e["difficulty"], 0) <= max_diff]

    return results


def search_exercises(query: str) -> list[dict]:
    """Search exercises by name."""
    q = query.lower()
    return [e for e in EXERCISE_DATABASE if q in e["name"].lower()]
